[build]
  command = "npm run build"
  publish = "dist"   # atau folder output-mu

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  # Suppress false positive secret detection
  NETLIFY_SKIP_FUNCTIONS_CACHE = "true"